name: PR-Checks

on:
  pull_request:
    branches:
    - main
    - develop

jobs:
  checkstyle:
    name: checkstyle
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK and Maven
        uses: actions/setup-java@v2
        with:
          java-version: '1.8' # Adjust to your project's Java version
          maven-version: '3.8' # Adjust to the desired Maven version

      - name: Package with Maven
        run: mvn clean package -DskipTests

      - name: Run Checkstyle
        run: mvn checkstyle:check
