name: PR-Checks

on:
  pull_request:
    branches:
    - main
    - develop

jobs:
  checkstyle:
    name: checkstyle
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          maven-version: '3.8'

      - name: Package with Maven
        run: mvn clean package -DskipTests

      - name: Run Checkstyle
        run: mvn checkstyle:check
